version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: sentiment-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/model:/app/model
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: sentiment-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped 